[package]
name = "host"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
serde_json = "1.0.142"
local-ip-address = "0.6.5"
serde = { version = "1.0.219", features = ["derive"] }